### ISSUE TITLE
Bug in Modifying scaling attacks in Foundry when there is an error in the shortcode

### ISSUE THREAD

**Issue by Winnihym** [Skyl3lazer/foundry-5e-monster-maker-v10#70]
Order to recreate error:
1) Create new scaling monster
2) Attach an attack to the monster (either a new scaling attack or one from the compendium)
![Screen1](https://github.com/user-attachments/assets/0f23b6f6-ffad-49a1-aed5-1d87558a0a76)
3) This all works correctly, and scales correctly under the monster attack as the level is changed
![Scaled to 10](https://github.com/user-attachments/assets/0cdcc626-2641-4105-8635-e7c33ddc0d7b)
4) If there is an error in the shortcode in the scaling attack (note XXXX instead of [damage], two errors pop up
![Screw up the formula](https://github.com/user-attachments/assets/88a5459f-575e-4ba0-8fb8-4d6f9c34c13a)
5) Can no longer modify the scaling attack, or close it, or modify the monster.
![Can no longer edit attack](https://github.com/user-attachments/assets/e00238b3-304f-4ab2-b07d-01447b2e84e9)

**Comment by Skyl3lazer** [comment]
Issue with dnd3.3, investigating

**Comment by Skyl3lazer** [comment]
Addressed in 2e1499694d09f7714c0a9aa4e3508fe672248a89 on dev
