### ISSUE TITLE
Version 12 of Foundry seems to have broken the program. 

### ISSUE THREAD

**Issue by zantetsukenV** [Skyl3lazer/foundry-5e-monster-maker-v10#72]
Version 12 of Foundry seems to have broken the program. I am getting the error: "Error detected in module. It is likely this module has not been updated for FVTT Version 12 Stable. (See JS Console). Help?

**Comment by Skyl3lazer** [comment]
See the other open issue. It is updated for v12, it is not updated for
DND5e 4.x
